# 【帮派商会】

# 交易会所
# 点击交易 -> 复制当前链接，找到 type=0&goods_id=3041
# https://dld.qzapp.z.qq.com/qpet/cgi-bin/phonepk?zapp_uin=&sid=&channel=0&g_ut=1&cmd=fac_corp&op=4&type=0&goods_id=3041
交易:
  小体力*10: type=0&goods_id=3001
  大体力*5: type=0&goods_id=3003
  经验药水*5: type=0&goods_id=3014
  大经验药水*1: type=0&goods_id=3015
  经验药水7天*5: type=0&goods_id=3019
  神来拳套*5: type=0&goods_id=3028
  被动经验7天*1: type=0&goods_id=3029
  孟婆汤*1: type=0&goods_id=3037
  挑战书*5: type=0&goods_id=3040
  真体力*5: type=0&goods_id=3041

  经验木简*10: type=1&goods_id=3178
  百炼钢*5: type=1&goods_id=3871

  奔流气息*5: type=2&goods_id=3636

# 兑换商店
# 兑换 -> 复制当前页面链接，找到 type_id=259
# https://dld.qzapp.z.qq.com/qpet/cgi-bin/phonepk?zapp_uin=&sid=&channel=0&g_ut=1&cmd=fac_corp&op=5&type_id=259
兑换:
  1级狂暴石*1: 251
  1级神愈石*1: 252
  2级狂暴石*1: 253
  1级狂暴石*2: 255
  1级神愈石*2: 256
  1级神愈石*5: 258
  1级狂暴石*10: 259
  1级神愈石*10: 260
  1级日曜石*1: 261
