# 【活动】企鹅吉利兑 兑换选择

# id  消耗  次数
# 1   180   1    泯灭·苍玉IV
# 2   180   1    破坏·银光IV
# 3   180   1    洞悉·异炎IV
# 4   180   1    破坏·锦月IV
# 5   20    25   V级万能碎片
# 6   2     100  熔炼乌金
# 7   2     20   玄铁令
# 8   1     30   挑战书

# 截止日的前一天（最后一个周四）兑换，比如28日结束，那么会在27日完成兑换
# 可以改变下面顺序或者删除不需要的，靠前的优先兑换
企鹅吉利兑:
  - 泯灭·苍玉IV
  - 破坏·银光IV
  - 洞悉·异炎IV
  - 破坏·锦月IV
  - V级万能碎片
  - 熔炼乌金
  - 玄铁令
  - 挑战书
