# 用于【竞技场】兑换商店兑换材料

# 3567  神秘精华  可以用来强化神装技能
# 3568  精武之魂  可以提升神装·神兵的生命加成
# 3569  守护之魂  可以提升神装·神凯的生命加成
# 3573  神兵原石  可以用来进阶神装·神兵
# 3574  软猥金丝  可以用来进阶神装·神铠
# 5435  河洛图书  可以用来提升助阵属性等级
# False 表示不兑换，如果兑换河洛图书，改为 5435
id: 5435

# 兑换次数，只能选 1 或 10
times: 10