# 【yaml】文件格式说明:
# 所有标点符号均使用英文,比如 : -
# 冒号: 与数据之间有一个空格
# 短横线- 与数据之间有一个空格
# 在行首加 # 会注释该行

# 【十二宫】通关关卡
# 1011 表示 双鱼宫
十二宫: 1011
# 白羊宫  1000
# 金牛宫  1001
# 双子宫  1002
# 巨蟹宫  1003
# 狮子宫  1004
# 处女宫  1005
# 天秤宫  1006
# 天蝎宫  1007
# 射手宫  1008
# 摩羯宫  1009
# 水瓶宫  1010
# 双鱼宫  1011

# 【幻境】通关关卡
# 20 表示 鹅王的试炼
幻境: 20
# 1 乐斗村
# 2 林松郊外
# 3 林松城
# 4 东海龙宫
# 5 踏云镇
# 6 摩云山
# 7 洞庭湖
# 8 苍莽山
# 9 玉龙湿地
# 10  玉龙雪山
# 11  狂沙台地
# 12  回声遗迹
# 13  悲叹山丘
# 14  黄沙漩涡
# 15  炎之洞窟
# 16  程管小镇
# 17  花果山
# 18  藏剑山庄
# 19  桃花剑冢
# 20  鹅王的试炼

# 【深渊之潮】通关关卡
# 4 表示 曲镜空洞
深渊之潮: 4
# 1 崎岖斗界
# 2 魂渡桥
# 3 须臾之河
# 4 曲镜空洞
# 5 光影迷界
# 6 吞厄源头
# 7 渊秘祭坛

# 【竞技场】商店兑换
# 5435 表示 河洛图书，，它被兑换10个；如果不想兑换任何材料改成 0
竞技场: 5435
# 3567  神秘精华  可以用来强化神装技能
# 3568  精武之魂  可以提升神装·神兵的生命加成
# 3569  守护之魂  可以提升神装·神凯的生命加成
# 3573  神兵原石  可以用来进阶神装·神兵
# 3574  软猥金丝  可以用来进阶神装·神铠
# 5435  河洛图书  可以用来提升助阵属性等级

# 【门派邀请赛】商店兑换
# 1246 表示 炼气石，它被兑换10个；如果不想兑换任何材料改成 0
门派邀请赛: 1246
# 1246  炼气石      可以用来强化门派上层心法
# 1247  门派强化书  可以用来强化门派武器和技能
# 1248  门派高香    可以用来上香获得门派贡献
# 1249  门派战书    可以用来增加同门切磋和门派邀请赛额外次数
# 1250  门派引荐书  可以用来变更门派

# 【帮派黄金联赛】是否参加防守、参战
# True 表示是；False 表示否
帮派黄金联赛: True

# 【历练】通关关卡
# 佣兵     BOSS                 npcid    佣兵属性
# 令狐冲   林松郊外 -> 凶尸       6034    造成必中伤害，1级最高20点，满级最高77点
# 丘处机   东海龙宫 -> 夜叉元帅   6074    抵挡对方伤害，1级最高30点，满级最高87点
# 小龙女   踏云镇 -> 霹雳头领     6094    回血3回合，1级每回合最高13点，满级最高39点
# 韦小宝   摩云山 -> 宋姜         6114    对方3回合不能使用武器技能，1级最高43%命中，满级100%
# 扫地僧   洞庭湖 -> 大鹏         6134    按比例反弹对方伤害3次，1级最高反弹16%，满级54%
# 丁春秋   林松城 -> 虾兵头目     6054    对方中毒3回合，1级每回合最多掉血10点，满级29点
# 鹤笔翁   苍莽山 -> 马大王       6154    降低对方敏捷3回合，1级最高12%，满级50%
# 韦一笑   玉龙湿地 -> 嗜血鬼王   6174     造成对方当前血量的百分比伤害，并吸取一半，1级最高13%，满级32%
# 赵  敏   玉龙雪山 -> 象仙       6194    概率抵消对方伤害1次，并回复30%伤害值的血量，1级最高43%发动，满级100%
历练:
  # 可以改变下面BOSS顺序或者加 # 注释掉不想打的BOSS
  - 6114
  - 6034
  - 6054
  - 6074
  - 6094
  - 6134
  - 6154
  - 6174
  - 6194

# 【帮派商会】
帮派商会:
  交易会所:
    # 点击交易 -> 复制当前链接，找到 type=0&goods_id=3041
    小体力*10: type=0&goods_id=3001
    大体力*5: type=0&goods_id=3003
    经验药水*5: type=0&goods_id=3014
    大经验药水*1: type=0&goods_id=3015
    经验药水7天*5: type=0&goods_id=3019
    神来拳套*5: type=0&goods_id=3028
    被动经验7天*1: type=0&goods_id=3029
    挑战书*5: type=0&goods_id=3040
    真体力*5: type=0&goods_id=3041
    经验木简*10: type=1&goods_id=3178
    百炼钢*5: type=1&goods_id=3871
    奔流气息*5: type=2&goods_id=3636
  兑换商店:
    # 点击兑换 -> 复制当前页面链接，找到 type_id=259
    1级狂暴石*1: 251
    1级神愈石*1: 252
    2级狂暴石*1: 253
    1级狂暴石*2: 255
    1级神愈石*2: 256
    1级神愈石*5: 258
    1级狂暴石*10: 259
    1级神愈石*10: 260
    1级日曜石*1: 261

# 【活动】
活动:
  企鹅吉利兑:
    # 截止日的前一天（最后一个周四）兑换，比如28日结束，那么会在27日完成兑换
    # id  消耗  次数
    # 1   180   1    泯灭·苍玉IV
    # 2   180   1    破坏·银光IV
    # 3   180   1    洞悉·异炎IV
    # 4   180   1    破坏·锦月IV
    # 5   20    25   V级万能碎片
    # 6   2     100  熔炼乌金
    # 7   2     20   玄铁令
    # 8   1     30   挑战书
    # 可以改变下面顺序或者删除不需要的，靠前的优先兑换
    - 玄铁令
    - 熔炼乌金
    - 泯灭·苍玉IV
    - 破坏·银光IV
    - 洞悉·异炎IV
    - 破坏·锦月IV
    - V级万能碎片
    - 挑战书
