# 【十二宫】默认挑战双鱼宫
# 白羊宫  1000
# 金牛宫  1001
# 双子宫  1002
# 巨蟹宫  1003
# 狮子宫  1004
# 处女宫  1005
# 天秤宫  1006
# 天蝎宫  1007
# 射手宫  1008
# 摩羯宫  1009
# 水瓶宫  1010
# 双鱼宫  1011
十二宫:
  id: 1011

# 【幻境】默认挑战鹅王的试炼
# 1 乐斗村
# 2 林松郊外
# 3 林松城
# 4 东海龙宫
# 5 踏云镇
# 6 摩云山
# 7 洞庭湖
# 8 苍莽山
# 9 玉龙湿地
# 10  玉龙雪山
# 11  狂沙台地
# 12  回声遗迹
# 13  悲叹山丘
# 14  黄沙漩涡
# 15  炎之洞窟
# 16  程管小镇
# 17  花果山
# 18  藏剑山庄
# 19  桃花剑冢
# 20  鹅王的试炼
幻境:
  id: 20

# 【深渊之潮】深渊秘境选择，默认 曲镜空洞
# 1 崎岖斗界
# 2 魂渡桥
# 3 须臾之河
# 4 曲镜空洞
# 5 光影迷界
# 6 吞厄源头
深渊之潮:
  id: 4

# 【历练】
# 佣兵     BOSS                 npcid    佣兵属性
# 令狐冲   林松郊外 -> 凶尸       6034    造成必中伤害，1级最高20点，满级最高77点
# 丘处机   东海龙宫 -> 夜叉元帅   6074    抵挡对方伤害，1级最高30点，满级最高87点
# 小龙女   踏云镇 -> 霹雳头领     6094    回血3回合，1级每回合最高13点，满级最高39点
# 韦小宝   摩云山 -> 宋姜         6114    对方3回合不能使用武器技能，1级最高43%命中，满级100%
# 扫地僧   洞庭湖 -> 大鹏         6134    按比例反弹对方伤害3次，1级最高反弹16%，满级54%
# 丁春秋   林松城 -> 虾兵头目     6054    对方中毒3回合，1级每回合最多掉血10点，满级29点
# 鹤笔翁   苍莽山 -> 马大王       6154    降低对方敏捷3回合，1级最高12%，满级50%
# 韦一笑   玉龙湿地 -> 嗜血鬼王   6174     造成对方当前血量的百分比伤害，并吸取一半，1级最高13%，满级32%
# 赵  敏   玉龙雪山 -> 象仙       6194    概率抵消对方伤害1次，并回复30%伤害值的血量，1级最高43%发动，满级100%
历练:
  id:
    # 可以改变下面BOSS顺序或者加 # 注释掉不想打的BOSS
    - 6114
    - 6034
    - 6054
    - 6074
    - 6094
    - 6134
    - 6154
    - 6174
    - 6194

# 【竞技场】默认兑换10个河洛图书
# 3567  神秘精华  可以用来强化神装技能
# 3568  精武之魂  可以提升神装·神兵的生命加成
# 3569  守护之魂  可以提升神装·神凯的生命加成
# 3573  神兵原石  可以用来进阶神装·神兵
# 3574  软猥金丝  可以用来进阶神装·神铠
# 5435  河洛图书  可以用来提升助阵属性等级
竞技场:
  # id 值为 0 表示不兑换，如果兑换河洛图书，改为 5435
  # times 表示兑换次数，只能选 1 或 10
  id: 5435
  times: 10

# 【门派邀请赛】默认兑换10个炼气石
# 1246  炼气石      可以用来强化门派上层心法
# 1247  门派强化书  可以用来强化门派武器和技能
# 1248  门派高香    可以用来上香获得门派贡献
# 1249  门派战书    可以用来增加同门切磋和门派邀请赛额外次数
# 1250  门派引荐书  可以用来变更门派
门派邀请赛:
  # id 值为 0 表示不兑换，如果兑换炼气石，改为 1246
  # times 表示兑换次数，只能选 1 或 10
  id: 1246
  times: 10

# 【帮派商会】
帮派商会:
  交易:
    # 交易会所
    # 点击交易 -> 复制当前链接，找到 type=0&goods_id=3041
    小体力*10: type=0&goods_id=3001
    大体力*5: type=0&goods_id=3003
    经验药水*5: type=0&goods_id=3014
    大经验药水*1: type=0&goods_id=3015
    经验药水7天*5: type=0&goods_id=3019
    神来拳套*5: type=0&goods_id=3028
    被动经验7天*1: type=0&goods_id=3029
    孟婆汤*1: type=0&goods_id=3037
    挑战书*5: type=0&goods_id=3040
    真体力*5: type=0&goods_id=3041
    经验木简*10: type=1&goods_id=3178
    百炼钢*5: type=1&goods_id=3871
    奔流气息*5: type=2&goods_id=3636
  兑换:
    # 兑换商店
    # 点击兑换 -> 复制当前页面链接，找到 type_id=259
    1级狂暴石*1: 251
    1级神愈石*1: 252
    2级狂暴石*1: 253
    1级狂暴石*2: 255
    1级神愈石*2: 256
    1级神愈石*5: 258
    1级狂暴石*10: 259
    1级神愈石*10: 260
    1级日曜石*1: 261

# 【活动】
活动:
  企鹅吉利兑:
    # 截止日的前一天（最后一个周四）兑换，比如28日结束，那么会在27日完成兑换
    # id  消耗  次数
    # 1   180   1    泯灭·苍玉IV
    # 2   180   1    破坏·银光IV
    # 3   180   1    洞悉·异炎IV
    # 4   180   1    破坏·锦月IV
    # 5   20    25   V级万能碎片
    # 6   2     100  熔炼乌金
    # 7   2     20   玄铁令
    # 8   1     30   挑战书
    # 可以改变下面顺序或者删除不需要的，靠前的优先兑换
    - 泯灭·苍玉IV
    - 破坏·银光IV
    - 洞悉·异炎IV
    - 破坏·锦月IV
    - V级万能碎片
    - 熔炼乌金
    - 玄铁令
    - 挑战书
  春联大赛:
    # 春联大赛
    # 左边上联，右边下联
    虎年腾大步: 兔岁展宏图
    虎辟长安道: 兔开大吉春
    虎跃前程去: 兔携好运来
    虎去雄风在: 兔来喜气浓
    虎带祥云去: 兔铺锦绣来
    虎蹄留胜迹: 兔角搏青云
    虎留英雄气: 兔会世纪风
    金虎辞旧岁: 银兔贺新春
    虎威惊盛世: 兔翰绘新春
    虎驰金世界: 兔唤玉乾坤
    虎声传捷报: 兔影抖春晖
    虎嘶飞雪里: 兔舞画图中
    兔归皓月亮: 花绽春光妍
    兔俊千山秀: 春暖万水清
    兔毫抒壮志: 燕梭织春光
    玉兔迎春至: 黄莺报喜来
    玉兔迎春到: 红梅祝福来
    玉兔蟾宫笑: 红梅五岭香
    卯时春入户: 兔岁喜盈门
    卯门生紫气: 兔岁报新春
    卯来四季美: 兔献百家福
    红梅迎春笑: 玉兔出月欢
    红梅赠虎岁: 彩烛耀兔年
    红梅迎雪放: 玉兔踏春来
    丁年歌盛世: 卯兔耀中华
    寅年春锦绣: 卯序业辉煌
    燕舞春光丽: 兔奔曙光新
    笙歌辞旧岁: 兔酒庆新春
    瑞雪兆丰年: 迎得玉兔归
    雪消狮子瘦: 月满兔儿肥

# 【背包】
背包:
  使用:
    # 使用 一次
    # 神来拳套(赠): 3030
    一等武林宝箱: 3047
    二等武林宝箱: 3048
    四等武林宝箱: 3050
    阅历羊皮卷: 3176
    # 经验木简: 3178
    贡献小笼包: 3356
    魂珠碎片宝箱: 3371
    阅历卷宗: 3381
    巅峰之战二等勋章: 3487
    巅峰之战一等勋章: 3488
    贡献叉烧包: 3503
    资源补给箱: 3671
    峨眉堂主7天: 3894
    斗技符小宝箱: 5710
    斗技符大宝箱: 5712
    元婴生命果: 5175
    3级星石礼盒: 5392
    佣兵碎片小宝箱: 5875
    佣兵碎片中宝箱: 5876
    佣兵碎片大宝箱: 5877
    神将碎片宝箱: 5878
  提前:
    # 部分靠前的物品会 供奉守护神
    小体力(10点): 3001
    中体力: 3002
    大体力(30点): 3003
    经验药水: 3014
    被动经验药水: 3043
    菜菜7天: 3115
    菜菜30天: 3116
    剑君7天: 3117
    剑君30天: 3118
    月敏7天: 3119
    月敏30天: 3120
    姜公7天: 3121
    教主7天: 3123
    帅帅7天: 3125
    源大侠7天: 3127
    邪神30天: 3132
    程管7天: 3140
    程管30天: 3141
    大色魔7天: 3142
    大色魔30天: 3143
    俊猴王7天: 3144
    马大师7天: 3148
    小王子30天: 3154
    江南大叔7天: 3155
    四姑娘7天: 3157
    回声之影30天: 3177
    跳跳虎变身卡365天: 6771
  # 下面没有什么作用，仅作记录
  # 贡献药水: 3038
  # 大经验药水: 3015
  # 经验药水7天: 3019
  # 神来拳套: 3028
  # 被动经验7天: 3029
  # 真体力(60点): 3041
  # 活力药水: 3105
  # 小活力药水: 3386
  # 真黄金卷轴: 5089
  # 零经验药水: 6332
