# 【历练】

# 佣兵     BOSS                 npcid    佣兵属性
# 令狐冲   林松郊外 -> 凶尸       6034    造成必中伤害，1级最高20点，满级最高77点
# 丘处机   东海龙宫 -> 夜叉元帅   6074    抵挡对方伤害，1级最高30点，满级最高87点
# 小龙女   踏云镇 -> 霹雳头领     6094    回血3回合，1级每回合最高13点，满级最高39点
# 韦小宝   摩云山 -> 宋姜         6114    对方3回合不能使用武器技能，1级最高43%命中，满级100%
# 扫地僧   洞庭湖 -> 大鹏         6134    按比例反弹对方伤害3次，1级最高反弹16%，满级54%
# 丁春秋   林松城 -> 虾兵头目     6054    对方中毒3回合，1级每回合最多掉血10点，满级29点
# 鹤笔翁   苍莽山 -> 马大王       6154    降低对方敏捷3回合，1级最高12%，满级50%
# 韦一笑   玉龙湿地 -> 嗜血鬼王   6174     造成对方当前血量的百分比伤害，并吸取一半，1级最高13%，满级32%
# 赵  敏   玉龙雪山 -> 象仙       6194    概率抵消对方伤害1次，并回复30%伤害值的血量，1级最高43%发动，满级100%

# 可以改变下面BOSS顺序或者加 # 注释掉不想打的BOSS
npcid:
  - 6114
  - 6034
  - 6054
  - 6074
  - 6094
  - 6134
  - 6154
  - 6174
  - 6194
