# 用于【门派邀请赛】兑换商店兑换材料

# 1246  炼气石      可以用来强化门派上层心法
# 1247  门派强化书  可以用来强化门派武器和技能
# 1248  门派高香    可以用来上香获得门派贡献
# 1249  门派战书    可以用来增加同门切磋和门派邀请赛额外次数
# 1250  门派引荐书  可以用来变更门派
# False 表示不兑换，如果兑换炼气石，改为 1246
type: False

# 兑换次数，只能选 1 或 10
times: 1
